version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@3.0.0

executors:
  docker:
    docker:
      - image: cimg/node:16.10

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Installing dependencies..."
          npm install

  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run: |
          echo "Running tests..."
          npm run test

build-and-push:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker
      - docker/check:
          docker-username: ${DOCKERHUB_USERNAME}
          docker-password: ${DOCKERHUB_PASSWORD}
      - run:
          name: Build Docker Image
          command: docker build -t $DOCKERHUB_USERNAME/myapp:${CIRCLE_SHA1} .
      - docker/push:
          image: $DOCKERHUB_USERNAME/myapp
          tag: ${CIRCLE_SHA1}

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - build-and-push:
          requires:
            - test