version: 2.1

orbs:
  node: circleci/node@5.0.1
  docker: circleci/docker@2.1.0  # Updated Docker Orb version

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Install Dependencies
          command: npm install
  test:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Tests
          command: npm run test
  publish:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Docker Login
          command: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/nodeapp:${CIRCLE_SHA1} .
      - run:
          name: Push Docker Image
          command: |
            docker push $DOCKERHUB_USERNAME/nodeapp:${CIRCLE_SHA1}

workflows:
  simple_workflow:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish:
          requires:
            - test
